### ISSUE TITLE
Word List in Function list in Inovice class is a reserved word.

### ISSUE THREAD

**Issue by mfadel85** [netinternet/parasut-v4#4]
Thanks very much, 
I would like to say that namespace Parasut;
the word list in the function below is a reserved word, I used this class one year ago with no problems, but recently when I am using, it didn't accept it, I faced this error:
Parse error: syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in /********/***/vendor/netinternet/parasut-v4/src/Invoice.php on line 7

    public function list($params = [])
    {
        return $this->client->request(
          'sales_invoices/',
          $params,
          'GET'
        );
    }
Centos Php 5.6 suphp nginx

I changed the function name to listing and it worked.

Best Wishes
Faddel

**Comment by hakanersu** [comment]
Thank you @mfadel85 i'll change this function to listInvoices
