### ISSUE TITLE
composer'da en son 1.0.13 sürümü var.

### ISSUE THREAD

**Issue by halukakin** [netinternet/parasut-v4#5]
Composer'da en son 1.0.13 sürümü var. 
https://packagist.org/packages/netinternet/parasut-v4

Composer'dan 1.0.19 şu anda çekilemiyor.

**Comment by hakanersu** [comment]
Bilgilendirme için teşekkürler uygun zamanda guncelleyecegim.

**Comment by hakanersu** [comment]
1.0.20 kullanabilirsiniz.

Tesekkurler.
